/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    fontFamily: {
      'aspekta-light': ['"Aspekta Light"', 'system-ui', 'sans-serif'],
      aspekta: ['Aspekta', 'system-ui', 'sans-serif'],
      'aspekta-semibold': ['"Aspekta SemiBold"', 'system-ui', 'sans-serif'],
      'aspekta-bold': ['"Aspekta Bold"', 'system-ui', 'sans-serif'],
    },
    extend: {
      colors: {
        'bgs-primary-earth': '#002e40',
        'bgs-primary-stone': '#ad9c70',
        'bgs-primary-white': '#fff',
        'bgs-primary-black': '#000',
        'bgs-alternate': '#505050',
        'bgs-alternate-disabled': '#b5b5b5',
        'bgs-secondary-lichen': '#99b096',
        'bgs-secondary-sky': '#7391bf',
        'bgs-secondary-sea': '#528791',
        'bgs-secondary-grass': '#8cb052',
        'bgs-secondary-haze': '#d48080',
        'bgs-secondary-clay': '#b87d33',
        'bgs-secondary-amber': '#f0a845',
        'bgs-secondary-sand': '#c4bd9c',
        'bgs-secondary-rock': '#a8a8a1',
        'bgs-secondary-earth': '#998a82',
        'bgs-secondary-slate': '#808082',
        'bgs-secondary-red': '#eb5757',
        'bgs-mono-black': '#252525',
        'bgs-mono-grey-1': '#e1e1e1',
        'bgs-mono-grey-2': '#e5e5e5',
        'bgs-mono-grey-3': '#b5b5b5',
        'bgs-mono-grey-4': '#505050',
        'bgs-state-success': '#007b40',
        'bgs-state-error': '#f03d3e',
        'bgs-state-warn': '#f0a845',
      },
      screens: {
        '3xl': '1830px',
      },
    },
  },
  plugins: [],
};
