interface ISubcatchments {
  [key: number]: string;
}

export const Subcatchments: ISubcatchments = {
  0: 'Birkin Brook - Mobberley Brook to River Bollin (including Rostherne Brook)',
  1: 'Birkin Brook - Source to Mobberley Brook',
  2: 'Black Brook (Upper Mersey)',
  3: 'Bollin (Ashley Mill to Manchester Ship Canal)',
  4: 'Bollin (River Dean to Ashley Mill)',
  5: 'Bollin (Source to Dean)',
  6: 'Chew Brook',
  7: 'Chorlton Brook (Princess Parkway to Mersey)',
  8: 'Crowden Great Brook',
  9: 'Dean (Bollington to Bollin)',
  10: 'Dean (Lamaload to Bollington)',
  11: 'Etherow (Glossop Brook to Goyt)',
  12: 'Etherow (Source to Woodhead Reservoir)',
  13: 'Etherow (Woodhead Res. to Glossop Bk.)',
  14: 'Fallowfield Brook',
  15: 'Glossop (Shelf) Brook (Source to Long Clough Brook)',
  16: 'Glossop Brook (Long Clough Brook to Etherow)',
  17: 'Goyt (Etherow to Mersey)',
  18: 'Goyt (Randall Carr Brook to Sett)',
  19: 'Goyt (Sett to Etherow)',
  20: 'Goyt (Source to Randall Carr Brook)',
  21: 'Harrop Brook',
  22: 'Heyden Brook',
  23: 'Hurst Brook',
  24: 'Long Clough Brook',
  25: 'Mersey (upstream of Manchester Ship Canal)',
  26: 'Mersey/ Manchester Ship Canal  (Irwell/Manchester Ship Canal to Bollin)',
  27: 'Micker (Norbury) Brook',
  28: 'Micker Brook',
  29: 'Mobberley Brook',
  30: 'Platt Brook (Source to Fallowfield Bk)',
  31: 'Poise Brook',
  32: 'Poynton Brook',
  33: 'Randall Carr Brook',
  34: 'Sett',
  35: 'Sinderland Brook',
  36: 'Sinderland Brook (Fairywell Bk and Baguley Bk)',
  37: 'Sugar Brook',
  38: 'Tame (Chew Brook to Swineshaw Brook)',
  39: 'Tame (Source to Chew Brook)',
  40: 'Tame (Swineshaw Brook to Mersey)',
  41: 'Timperley Brook',
  42: 'Todd Brook',
  43: 'Wilson Brook',
};
